class CapturedException(Exception):
    pass


class AnalysisException(CapturedException):
    pass
